export interface SpermData {
    idade: string,
    peso: string,
    ec: string,
    ce: string,
    temp_retal: string,
    temp_amb: string,
    umidade: string,
    mov_flanco: string,
    hora: string,
    turbilhao: string,
    mot_moveis: string,
    vigor: string,
    volume: string,
    zptz_106: string,
    zptz_totais: string,
    def_mai: string,
    def_mai_percent: string,
    def_men: string,
    def_men_percent: string,
    normais: string,
    normais_percent: string
}