export interface SpermData {
    idade: number,
    peso: number,
    ec: number,
    ce: number,
    temp_amb: number,
    temp_retal: number,
    umidade: number,
    mov_flanco: number,
    turbilhao: number,
    mot_moveis: number,
    vigor: number,
    volume: number,
    zptz_106: number,
    // zptz_totais: number,
    def_mai: number,
    def_mai_percent: number,
    // def_men: string,
    // def_men_percent: string,
    normais: number,
    normais_percent: number
}